# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about-keffinn.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1440, 900)
        self.background = QtWidgets.QWidget(Dialog)
        self.background.setGeometry(QtCore.QRect(0, 0, 1440, 900))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.background.setFont(font)
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("QWidget#background{\n"
"background:url(:/img/background.png);\n"
"};")
        self.background.setObjectName("background")
        self.label = QtWidgets.QLabel(self.background)
        self.label.setGeometry(QtCore.QRect(550, 180, 370, 265))
        self.label.setStyleSheet("QLabel{\n"
"background-image:url(:/img/logo_putih.png);\n"
"background-color:rgba(0,0,0,0);\n"
"};")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/logo_putih.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.background)
        self.label_2.setGeometry(QtCore.QRect(560, 70, 361, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.background)
        self.label_3.setGeometry(QtCore.QRect(0, 469, 1440, 571))
        self.label_3.setStyleSheet("width: 1440px;\n"
"height: 600px;\n"
"background-color: #4A8CB0; \n"
"border-top-left-radius: 40px;\n"
"border-top-right-radius: 40px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.background)
        self.label_4.setGeometry(QtCore.QRect(10, 480, 1421, 411))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TENTANG</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">EYE HEAR U adalah aplikasi inovatif yang dirancang untuk membantu penyandang disabilitas tunadaksa dalam </span></p><p align=\"center\"><span style=\" color:#ffffff;\">mengoperasikan komputer imgara mandiri dan nyaman. Dengan teknologi eye tracking dan voice command, </span></p><p align=\"center\"><span style=\" color:#ffffff;\">pengguna dapat mengontrol kursor, mengetik, dan menavigasi layar tanpa perlu menggunakan tangan.<br/></span></p><p align=\"center\"><span style=\" color:#ffffff;\">Kami percaya bahwa aksesibilitas digital adalah hak semua orang. Dengan EYE HEAR U, kami menghadirkan solusi </span></p><p align=\"center\"><span style=\" color:#ffffff;\">terjangkau, inklusif, dan mudah digunakan, memungkinkan siapa pun untuk terhubung dengan dunia digital dengan lebih mudah.</span></p></body></html>"))
from src import keffinn_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
